import assert from "node:assert/strict";
import { chmodSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { delimiter, join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import test from "node:test";

const script = resolve("scripts/sync-agent-instructions.sh");
const marker = "<!-- generated by agent/scripts/sync-agent-instructions.sh from AGENTS.MD plus instruction overlays; do not edit -->";

function fixture(context, { overlay, tool } = {}) {
  const root = mkdtempSync(join(tmpdir(), "agent-instructions-"));
  context.after(() => rmSync(root, { recursive: true, force: true }));
  const home = join(root, "home");
  const bin = join(root, "bin");
  const overlays = join(root, "manager", "instructions");
  mkdirSync(home, { recursive: true });
  mkdirSync(bin, { recursive: true });
  mkdirSync(overlays, { recursive: true });
  const canonical = join(root, "AGENTS.MD");
  writeFileSync(canonical, "# canonical\n- shared rule\n");
  if (overlay) writeFileSync(join(overlays, "gated.md"), overlay);
  if (tool) {
    writeFileSync(join(bin, tool), "#!/bin/sh\nexit 0\n");
    chmodSync(join(bin, tool), 0o755);
  }
  const run = (...args) =>
    spawnSync("/bin/bash", [script, "--cli", "claude", "--cli", "codex", ...args], {
      encoding: "utf8",
      env: {
        HOME: home,
        PATH: [bin, "/usr/bin", "/bin"].join(delimiter),
        AGENT_INSTRUCTIONS_SOURCE: canonical,
        AGENT_INSTRUCTIONS_OVERLAYS: overlays,
      },
    });
  return { home, bin, canonical, overlays, run, claude: join(home, ".claude", "CLAUDE.md"), codex: join(home, ".codex", "AGENTS.md") };
}

const gated = "<!-- requires: mission-work -->\n## Private rule\n- only where mission-work exists\n";

test("without overlays every target is a symlink and check passes", (context) => {
  const f = fixture(context);
  const sync = f.run();
  assert.equal(sync.status, 0, sync.stderr);
  assert.match(sync.stdout, /linked=2 rendered=0 preserved=0 overlays=none/);
  assert.ok(lstatSync(f.claude).isSymbolicLink());
  assert.equal(f.run("--check").status, 0);
});

test("an overlay whose required command is missing leaves symlinks", (context) => {
  const f = fixture(context, { overlay: gated });
  const sync = f.run();
  assert.equal(sync.status, 0, sync.stderr);
  assert.match(sync.stdout, /linked=2 rendered=0 .*overlays=none/);
  assert.ok(lstatSync(f.codex).isSymbolicLink());
});

test("an overlay whose required command exists renders a generated file", (context) => {
  const f = fixture(context, { overlay: gated, tool: "mission-work" });
  const sync = f.run();
  assert.equal(sync.status, 0, sync.stderr);
  assert.match(sync.stdout, /linked=0 rendered=2 preserved=0 overlays=gated.md/);
  assert.ok(!lstatSync(f.claude).isSymbolicLink());
  const content = readFileSync(f.claude, "utf8");
  assert.ok(content.startsWith(`${marker}\n# canonical\n- shared rule\n`));
  assert.match(content, /<!-- overlay: gated.md -->\n## Private rule\n- only where mission-work exists\n$/);
  assert.doesNotMatch(content, /requires: mission-work/);
  assert.equal(f.run("--check").status, 0);
  assert.match(f.run("--check").stdout, /rendered=2/);
});

test("--public-only ignores overlays even when the command exists", (context) => {
  const f = fixture(context, { overlay: gated, tool: "mission-work" });
  const sync = f.run("--public-only");
  assert.equal(sync.status, 0, sync.stderr);
  assert.match(sync.stdout, /linked=2 rendered=0/);
  assert.ok(lstatSync(f.claude).isSymbolicLink());
});

test("check reports drift when the canonical file changes, and sync re-renders", (context) => {
  const f = fixture(context, { overlay: gated, tool: "mission-work" });
  assert.equal(f.run().status, 0);
  writeFileSync(f.canonical, "# canonical v2\n");
  const check = f.run("--check");
  assert.equal(check.status, 1);
  assert.match(check.stderr, /stale overlay render: .*CLAUDE.md/);
  assert.equal(f.run().status, 0);
  assert.match(readFileSync(f.codex, "utf8"), /# canonical v2/);
});

test("a generated file falls back to a symlink once the command disappears", (context) => {
  const f = fixture(context, { overlay: gated, tool: "mission-work" });
  assert.equal(f.run().status, 0);
  rmSync(join(f.bin, "mission-work"));
  const check = f.run("--check");
  assert.equal(check.status, 1);
  assert.match(check.stderr, /stale overlay render/);
  const sync = f.run();
  assert.equal(sync.status, 0, sync.stderr);
  assert.match(sync.stdout, /linked=2 rendered=0/);
  assert.ok(lstatSync(f.claude).isSymbolicLink());
});

test("a preserved pointer file is left alone even when overlays apply", (context) => {
  const f = fixture(context, { overlay: gated, tool: "mission-work" });
  mkdirSync(join(f.home, ".codex"), { recursive: true });
  writeFileSync(f.codex, "READ ~/Projects/agent/AGENTS.MD BEFORE ANYTHING (skip if missing).\n\nlocal notes\n");
  const sync = f.run();
  assert.equal(sync.status, 0, sync.stderr);
  assert.match(sync.stdout, /rendered=1 preserved=1/);
  assert.match(readFileSync(f.codex, "utf8"), /local notes/);
});
