#!/usr/bin/env bash
set -euo pipefail

mode="sync"
all_clis=0
include_private=1
selected_clis=()
supported_clis=(codex claude opencode gemini copilot)

usage() {
  cat <<'USAGE'
usage: sync-agent-instructions.sh [--check] [--public-only] [--all-clis] [--cli NAME]...

Link the canonical AGENTS.MD into detected CLIs' user-level instruction paths.
Existing regular files are preserved and receive the canonical pointer as their
first line.

Private instruction overlays (default: ../manager/instructions/*.md) are
appended only on machines that satisfy each overlay's first-line gate,
`<!-- requires: cmd[, cmd...] -->`. When at least one overlay applies, the
destination becomes a generated regular file (canonical + overlays) instead of
a symlink; when none apply, the symlink is restored.

Options:
  --check        report drift without changing files
  --public-only  ignore private instruction overlays
  --all-clis     configure every supported CLI, installed or not
  --cli NAME     configure home, codex, claude, opencode, gemini, or copilot;
                 repeat to configure multiple CLIs

Environment overrides:
  AGENT_INSTRUCTIONS_SOURCE    canonical file (default: ../AGENTS.MD)
  AGENT_INSTRUCTIONS_POINTER   path written into preserved files
  AGENT_INSTRUCTIONS_OVERLAYS  overlay directory (default: ../../manager/instructions)
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check) mode="check" ;;
    --public-only) include_private=0 ;;
    --all-clis) all_clis=1 ;;
    --cli)
      [[ $# -ge 2 ]] || { echo "error: --cli requires a value" >&2; exit 2; }
      selected_clis+=("$2")
      shift
      ;;
    -h|--help) usage; exit 0 ;;
    *) echo "error: unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
  shift
done

if [[ "$all_clis" -eq 1 && "${#selected_clis[@]}" -gt 0 ]]; then
  echo "error: --all-clis and --cli cannot be used together" >&2
  exit 2
fi

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
canonical_source="${AGENT_INSTRUCTIONS_SOURCE:-$repo_root/AGENTS.MD}"
pointer_path="${AGENT_INSTRUCTIONS_POINTER:-~/Projects/agent/AGENTS.MD}"
pointer_line="READ $pointer_path BEFORE ANYTHING (skip if missing)."
overlay_root="${AGENT_INSTRUCTIONS_OVERLAYS:-$repo_root/../manager/instructions}"
generated_marker="<!-- generated by agent/scripts/sync-agent-instructions.sh from AGENTS.MD plus instruction overlays; do not edit -->"

if [[ ! -f "$canonical_source" ]]; then
  echo "error: canonical instructions not found: $canonical_source" >&2
  exit 1
fi
canonical_source="$(cd "$(dirname "$canonical_source")" && pwd)/$(basename "$canonical_source")"

# Overlay gate: first line `<!-- requires: a, b -->`. Prints the command list.
overlay_requires() {
  sed -n '1s/^<!-- *requires: *\(.*[^ ]\) *-->$/\1/p' "$1" | tr ',' ' '
}

overlay_applies() {
  local overlay="$1" command_name
  for command_name in $(overlay_requires "$overlay"); do
    command -v "$command_name" >/dev/null 2>&1 || return 1
  done
  return 0
}

overlay_body() {
  if [[ -n "$(overlay_requires "$1")" ]]; then
    sed '1d' "$1"
  else
    cat "$1"
  fi
}

overlays=()
if [[ "$include_private" -eq 1 && -d "$overlay_root" ]]; then
  overlay_root="$(cd "$overlay_root" && pwd)"
  for overlay in "$overlay_root"/*.md; do
    [[ -f "$overlay" ]] || continue
    overlay_applies "$overlay" && overlays+=("$overlay")
  done
fi

rendered_expected=""
if [[ "${#overlays[@]}" -gt 0 ]]; then
  rendered_expected="$(mktemp "${TMPDIR:-/tmp}/agent-instructions.XXXXXX")"
  trap 'rm -f "$rendered_expected"' EXIT
  {
    printf '%s\n' "$generated_marker"
    cat "$canonical_source"
    for overlay in "${overlays[@]}"; do
      printf '\n<!-- overlay: %s -->\n' "$(basename "$overlay")"
      overlay_body "$overlay"
    done
  } > "$rendered_expected"
fi

if [[ "${#selected_clis[@]}" -eq 0 ]]; then
  selected_clis=(home)
  for cli_name in "${supported_clis[@]}"; do
    if [[ "$all_clis" -eq 1 ]] || command -v "$cli_name" >/dev/null 2>&1; then
      selected_clis+=("$cli_name")
    fi
  done
fi

targets=()
cli_names=()
for cli_name in "${selected_clis[@]}"; do
  case "$cli_name" in
    home) destination="$HOME/AGENTS.md" ;;
    codex) destination="$HOME/.codex/AGENTS.md" ;;
    claude) destination="$HOME/.claude/CLAUDE.md" ;;
    opencode) destination="$HOME/.config/opencode/AGENTS.md" ;;
    gemini) destination="$HOME/.gemini/GEMINI.md" ;;
    copilot) destination="$HOME/.github/copilot-instructions.md" ;;
    *) echo "error: unknown CLI: $cli_name" >&2; exit 2 ;;
  esac

  already_selected=0
  if [[ "${#cli_names[@]}" -gt 0 ]]; then
    for existing_cli in "${cli_names[@]}"; do
      [[ "$existing_cli" == "$cli_name" ]] && already_selected=1
    done
  fi
  [[ "$already_selected" -eq 1 ]] && continue
  cli_names+=("$cli_name")
  targets+=("$destination")
done

failures=0
linked=0
rendered=0
preserved=0

is_generated() {
  [[ -f "$1" && ! -L "$1" && "$(sed -n '1p' "$1")" == "$generated_marker" ]]
}

write_rendered() {
  local destination="$1" temporary
  mkdir -p "$(dirname "$destination")"
  temporary="$(mktemp "${destination}.tmp.XXXXXX")"
  cp "$rendered_expected" "$temporary"
  chmod 0644 "$temporary"
  [[ -L "$destination" ]] && rm -f "$destination"
  mv "$temporary" "$destination"
}

for destination in "${targets[@]}"; do
  if [[ -n "$rendered_expected" ]]; then
    if is_generated "$destination" && cmp -s "$rendered_expected" "$destination"; then
      rendered=$((rendered + 1))
      continue
    fi
    if [[ -L "$destination" ]] || is_generated "$destination" || [[ ! -e "$destination" ]]; then
      if [[ "$mode" == "check" ]]; then
        echo "stale overlay render: $destination" >&2
        failures=$((failures + 1))
      else
        write_rendered "$destination"
        rendered=$((rendered + 1))
      fi
      continue
    fi
  elif is_generated "$destination"; then
    # Overlays no longer apply here; fall back to the plain symlink.
    if [[ "$mode" == "check" ]]; then
      echo "stale overlay render: $destination" >&2
      failures=$((failures + 1))
    else
      rm -f "$destination"
      ln -s "$canonical_source" "$destination"
      linked=$((linked + 1))
    fi
    continue
  fi

  if [[ -L "$destination" ]]; then
    if [[ "$(readlink "$destination")" == "$canonical_source" && -r "$destination" ]]; then
      linked=$((linked + 1))
      continue
    fi

    if [[ "$mode" == "check" ]]; then
      echo "mismatch: $destination -> $canonical_source" >&2
      failures=$((failures + 1))
    else
      ln -sfn "$canonical_source" "$destination"
      linked=$((linked + 1))
    fi
    continue
  fi

  if [[ -e "$destination" && ! -f "$destination" ]]; then
    echo "error: instruction target is not a file: $destination" >&2
    failures=$((failures + 1))
    continue
  fi

  if [[ -f "$destination" ]]; then
    if [[ "$(sed -n '1p' "$destination")" == "$pointer_line" ]]; then
      preserved=$((preserved + 1))
      continue
    fi

    if [[ "$mode" == "check" ]]; then
      echo "missing pointer: $destination" >&2
      failures=$((failures + 1))
      continue
    fi

    temporary="$(mktemp "${destination}.tmp.XXXXXX")"
    {
      printf '%s\n\n' "$pointer_line"
      awk -v pointer="$pointer_line" '$0 != pointer { print }' "$destination"
    } > "$temporary"
    if file_mode="$(stat -f '%Lp' "$destination" 2>/dev/null)"; then
      chmod "$file_mode" "$temporary"
    else
      chmod "$(stat -c '%a' "$destination")" "$temporary"
    fi
    mv "$temporary" "$destination"
    preserved=$((preserved + 1))
    continue
  fi

  if [[ "$mode" == "check" ]]; then
    echo "missing: $destination" >&2
    failures=$((failures + 1))
  else
    mkdir -p "$(dirname "$destination")"
    ln -s "$canonical_source" "$destination"
    linked=$((linked + 1))
  fi
done

if [[ "$failures" -ne 0 ]]; then
  echo "instruction sync failed: $failures issue(s)" >&2
  exit 1
fi

overlay_list="none"
if [[ "${#overlays[@]}" -gt 0 ]]; then
  overlay_names=()
  for overlay in "${overlays[@]}"; do overlay_names+=("$(basename "$overlay")"); done
  overlay_list="$(IFS=,; echo "${overlay_names[*]}")"
fi
cli_list="$(IFS=,; echo "${cli_names[*]}")"
echo "instructions $mode complete: linked=$linked rendered=$rendered preserved=$preserved overlays=$overlay_list clis=$cli_list"
